#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="enrollment")]
	public partial class EnrollmentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertstud_account(stud_account instance);
    partial void Updatestud_account(stud_account instance);
    partial void Deletestud_account(stud_account instance);
    partial void Insertcourse_tbl(course_tbl instance);
    partial void Updatecourse_tbl(course_tbl instance);
    partial void Deletecourse_tbl(course_tbl instance);
    partial void Insertenrollment_tbl(enrollment_tbl instance);
    partial void Updateenrollment_tbl(enrollment_tbl instance);
    partial void Deleteenrollment_tbl(enrollment_tbl instance);
    partial void Insertins_tbl(ins_tbl instance);
    partial void Updateins_tbl(ins_tbl instance);
    partial void Deleteins_tbl(ins_tbl instance);
    partial void Insertsubject_tbl(subject_tbl instance);
    partial void Updatesubject_tbl(subject_tbl instance);
    partial void Deletesubject_tbl(subject_tbl instance);
    #endregion
		
		public EnrollmentDataContext() : 
				base(global::Enrollment_System.Properties.Settings.Default.enrollmentConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EnrollmentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<stud_account> stud_accounts
		{
			get
			{
				return this.GetTable<stud_account>();
			}
		}
		
		public System.Data.Linq.Table<course_tbl> course_tbls
		{
			get
			{
				return this.GetTable<course_tbl>();
			}
		}
		
		public System.Data.Linq.Table<enrollment_tbl> enrollment_tbls
		{
			get
			{
				return this.GetTable<enrollment_tbl>();
			}
		}
		
		public System.Data.Linq.Table<ins_tbl> ins_tbls
		{
			get
			{
				return this.GetTable<ins_tbl>();
			}
		}
		
		public System.Data.Linq.Table<subject_tbl> subject_tbls
		{
			get
			{
				return this.GetTable<subject_tbl>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_password")]
		public ISingleResult<check_passwordResult> check_password([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, pass);
			return ((ISingleResult<check_passwordResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_username")]
		public ISingleResult<check_usernameResult> check_username([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<check_usernameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.create_account")]
		public int create_account([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> bd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string addrss, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, password, fname, mname, lname, bd, age, addrss, email, tel);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_studentacc")]
		public ISingleResult<check_studentaccResult> check_studentacc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<check_studentaccResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check_studentpass")]
		public ISingleResult<check_studentpassResult> check_studentpass([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
			return ((ISingleResult<check_studentpassResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_course")]
		public ISingleResult<get_courseResult> get_course()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<get_courseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_info")]
		public ISingleResult<get_infoResult> get_info([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<get_infoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_id;
		
		private string _username;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stud_account")]
	public partial class stud_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stud_id;
		
		private string _stud_username;
		
		private string _stud_password;
		
		private string _stud_fname;
		
		private string _stud_mname;
		
		private string _stud_lname;
		
		private System.Nullable<System.DateTime> _stud_bd;
		
		private System.Nullable<int> _stud_age;
		
		private string _stud_address;
		
		private string _stud_email;
		
		private string _stud_tel;
		
		private string _stud_isActive;
		
		private EntitySet<enrollment_tbl> _enrollment_tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstud_idChanging(int value);
    partial void Onstud_idChanged();
    partial void Onstud_usernameChanging(string value);
    partial void Onstud_usernameChanged();
    partial void Onstud_passwordChanging(string value);
    partial void Onstud_passwordChanged();
    partial void Onstud_fnameChanging(string value);
    partial void Onstud_fnameChanged();
    partial void Onstud_mnameChanging(string value);
    partial void Onstud_mnameChanged();
    partial void Onstud_lnameChanging(string value);
    partial void Onstud_lnameChanged();
    partial void Onstud_bdChanging(System.Nullable<System.DateTime> value);
    partial void Onstud_bdChanged();
    partial void Onstud_ageChanging(System.Nullable<int> value);
    partial void Onstud_ageChanged();
    partial void Onstud_addressChanging(string value);
    partial void Onstud_addressChanged();
    partial void Onstud_emailChanging(string value);
    partial void Onstud_emailChanged();
    partial void Onstud_telChanging(string value);
    partial void Onstud_telChanged();
    partial void Onstud_isActiveChanging(string value);
    partial void Onstud_isActiveChanged();
    #endregion
		
		public stud_account()
		{
			this._enrollment_tbls = new EntitySet<enrollment_tbl>(new Action<enrollment_tbl>(this.attach_enrollment_tbls), new Action<enrollment_tbl>(this.detach_enrollment_tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stud_id
		{
			get
			{
				return this._stud_id;
			}
			set
			{
				if ((this._stud_id != value))
				{
					this.Onstud_idChanging(value);
					this.SendPropertyChanging();
					this._stud_id = value;
					this.SendPropertyChanged("stud_id");
					this.Onstud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_username", DbType="VarChar(50)")]
		public string stud_username
		{
			get
			{
				return this._stud_username;
			}
			set
			{
				if ((this._stud_username != value))
				{
					this.Onstud_usernameChanging(value);
					this.SendPropertyChanging();
					this._stud_username = value;
					this.SendPropertyChanged("stud_username");
					this.Onstud_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_password", DbType="VarChar(50)")]
		public string stud_password
		{
			get
			{
				return this._stud_password;
			}
			set
			{
				if ((this._stud_password != value))
				{
					this.Onstud_passwordChanging(value);
					this.SendPropertyChanging();
					this._stud_password = value;
					this.SendPropertyChanged("stud_password");
					this.Onstud_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50)")]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this.Onstud_fnameChanging(value);
					this.SendPropertyChanging();
					this._stud_fname = value;
					this.SendPropertyChanged("stud_fname");
					this.Onstud_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_mname", DbType="VarChar(50)")]
		public string stud_mname
		{
			get
			{
				return this._stud_mname;
			}
			set
			{
				if ((this._stud_mname != value))
				{
					this.Onstud_mnameChanging(value);
					this.SendPropertyChanging();
					this._stud_mname = value;
					this.SendPropertyChanged("stud_mname");
					this.Onstud_mnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50)")]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this.Onstud_lnameChanging(value);
					this.SendPropertyChanging();
					this._stud_lname = value;
					this.SendPropertyChanged("stud_lname");
					this.Onstud_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_bd", DbType="Date")]
		public System.Nullable<System.DateTime> stud_bd
		{
			get
			{
				return this._stud_bd;
			}
			set
			{
				if ((this._stud_bd != value))
				{
					this.Onstud_bdChanging(value);
					this.SendPropertyChanging();
					this._stud_bd = value;
					this.SendPropertyChanged("stud_bd");
					this.Onstud_bdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_age", DbType="Int")]
		public System.Nullable<int> stud_age
		{
			get
			{
				return this._stud_age;
			}
			set
			{
				if ((this._stud_age != value))
				{
					this.Onstud_ageChanging(value);
					this.SendPropertyChanging();
					this._stud_age = value;
					this.SendPropertyChanged("stud_age");
					this.Onstud_ageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_address", DbType="VarChar(MAX)")]
		public string stud_address
		{
			get
			{
				return this._stud_address;
			}
			set
			{
				if ((this._stud_address != value))
				{
					this.Onstud_addressChanging(value);
					this.SendPropertyChanging();
					this._stud_address = value;
					this.SendPropertyChanged("stud_address");
					this.Onstud_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_email", DbType="VarChar(255)")]
		public string stud_email
		{
			get
			{
				return this._stud_email;
			}
			set
			{
				if ((this._stud_email != value))
				{
					this.Onstud_emailChanging(value);
					this.SendPropertyChanging();
					this._stud_email = value;
					this.SendPropertyChanged("stud_email");
					this.Onstud_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_tel", DbType="VarChar(50)")]
		public string stud_tel
		{
			get
			{
				return this._stud_tel;
			}
			set
			{
				if ((this._stud_tel != value))
				{
					this.Onstud_telChanging(value);
					this.SendPropertyChanging();
					this._stud_tel = value;
					this.SendPropertyChanged("stud_tel");
					this.Onstud_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_isActive", DbType="VarChar(20)")]
		public string stud_isActive
		{
			get
			{
				return this._stud_isActive;
			}
			set
			{
				if ((this._stud_isActive != value))
				{
					this.Onstud_isActiveChanging(value);
					this.SendPropertyChanging();
					this._stud_isActive = value;
					this.SendPropertyChanged("stud_isActive");
					this.Onstud_isActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stud_account_enrollment_tbl", Storage="_enrollment_tbls", ThisKey="stud_id", OtherKey="stud_id")]
		public EntitySet<enrollment_tbl> enrollment_tbls
		{
			get
			{
				return this._enrollment_tbls;
			}
			set
			{
				this._enrollment_tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enrollment_tbls(enrollment_tbl entity)
		{
			this.SendPropertyChanging();
			entity.stud_account = this;
		}
		
		private void detach_enrollment_tbls(enrollment_tbl entity)
		{
			this.SendPropertyChanging();
			entity.stud_account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.course_tbl")]
	public partial class course_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _course_id;
		
		private string _course_name;
		
		private EntitySet<enrollment_tbl> _enrollment_tbls;
		
		private EntitySet<subject_tbl> _subject_tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncourse_idChanging(int value);
    partial void Oncourse_idChanged();
    partial void Oncourse_nameChanging(string value);
    partial void Oncourse_nameChanged();
    #endregion
		
		public course_tbl()
		{
			this._enrollment_tbls = new EntitySet<enrollment_tbl>(new Action<enrollment_tbl>(this.attach_enrollment_tbls), new Action<enrollment_tbl>(this.detach_enrollment_tbls));
			this._subject_tbls = new EntitySet<subject_tbl>(new Action<subject_tbl>(this.attach_subject_tbls), new Action<subject_tbl>(this.detach_subject_tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this.Oncourse_nameChanging(value);
					this.SendPropertyChanging();
					this._course_name = value;
					this.SendPropertyChanged("course_name");
					this.Oncourse_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_tbl_enrollment_tbl", Storage="_enrollment_tbls", ThisKey="course_id", OtherKey="course_id")]
		public EntitySet<enrollment_tbl> enrollment_tbls
		{
			get
			{
				return this._enrollment_tbls;
			}
			set
			{
				this._enrollment_tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_tbl_subject_tbl", Storage="_subject_tbls", ThisKey="course_id", OtherKey="course_id")]
		public EntitySet<subject_tbl> subject_tbls
		{
			get
			{
				return this._subject_tbls;
			}
			set
			{
				this._subject_tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enrollment_tbls(enrollment_tbl entity)
		{
			this.SendPropertyChanging();
			entity.course_tbl = this;
		}
		
		private void detach_enrollment_tbls(enrollment_tbl entity)
		{
			this.SendPropertyChanging();
			entity.course_tbl = null;
		}
		
		private void attach_subject_tbls(subject_tbl entity)
		{
			this.SendPropertyChanging();
			entity.course_tbl = this;
		}
		
		private void detach_subject_tbls(subject_tbl entity)
		{
			this.SendPropertyChanging();
			entity.course_tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enrollment_tbl")]
	public partial class enrollment_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _enrollment_id;
		
		private string _enrollment_yearlevel;
		
		private System.Nullable<System.DateTime> _enrollment_date;
		
		private string _enrollment_status;
		
		private System.Nullable<int> _stud_id;
		
		private System.Nullable<int> _course_id;
		
		private EntityRef<course_tbl> _course_tbl;
		
		private EntityRef<stud_account> _stud_account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onenrollment_idChanging(int value);
    partial void Onenrollment_idChanged();
    partial void Onenrollment_yearlevelChanging(string value);
    partial void Onenrollment_yearlevelChanged();
    partial void Onenrollment_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onenrollment_dateChanged();
    partial void Onenrollment_statusChanging(string value);
    partial void Onenrollment_statusChanged();
    partial void Onstud_idChanging(System.Nullable<int> value);
    partial void Onstud_idChanged();
    partial void Oncourse_idChanging(System.Nullable<int> value);
    partial void Oncourse_idChanged();
    #endregion
		
		public enrollment_tbl()
		{
			this._course_tbl = default(EntityRef<course_tbl>);
			this._stud_account = default(EntityRef<stud_account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enrollment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int enrollment_id
		{
			get
			{
				return this._enrollment_id;
			}
			set
			{
				if ((this._enrollment_id != value))
				{
					this.Onenrollment_idChanging(value);
					this.SendPropertyChanging();
					this._enrollment_id = value;
					this.SendPropertyChanged("enrollment_id");
					this.Onenrollment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enrollment_yearlevel", DbType="VarChar(20)")]
		public string enrollment_yearlevel
		{
			get
			{
				return this._enrollment_yearlevel;
			}
			set
			{
				if ((this._enrollment_yearlevel != value))
				{
					this.Onenrollment_yearlevelChanging(value);
					this.SendPropertyChanging();
					this._enrollment_yearlevel = value;
					this.SendPropertyChanged("enrollment_yearlevel");
					this.Onenrollment_yearlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enrollment_date", DbType="Date")]
		public System.Nullable<System.DateTime> enrollment_date
		{
			get
			{
				return this._enrollment_date;
			}
			set
			{
				if ((this._enrollment_date != value))
				{
					this.Onenrollment_dateChanging(value);
					this.SendPropertyChanging();
					this._enrollment_date = value;
					this.SendPropertyChanged("enrollment_date");
					this.Onenrollment_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enrollment_status", DbType="VarChar(20)")]
		public string enrollment_status
		{
			get
			{
				return this._enrollment_status;
			}
			set
			{
				if ((this._enrollment_status != value))
				{
					this.Onenrollment_statusChanging(value);
					this.SendPropertyChanging();
					this._enrollment_status = value;
					this.SendPropertyChanged("enrollment_status");
					this.Onenrollment_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", DbType="Int")]
		public System.Nullable<int> stud_id
		{
			get
			{
				return this._stud_id;
			}
			set
			{
				if ((this._stud_id != value))
				{
					if (this._stud_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onstud_idChanging(value);
					this.SendPropertyChanging();
					this._stud_id = value;
					this.SendPropertyChanged("stud_id");
					this.Onstud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="Int")]
		public System.Nullable<int> course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					if (this._course_tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_tbl_enrollment_tbl", Storage="_course_tbl", ThisKey="course_id", OtherKey="course_id", IsForeignKey=true)]
		public course_tbl course_tbl
		{
			get
			{
				return this._course_tbl.Entity;
			}
			set
			{
				course_tbl previousValue = this._course_tbl.Entity;
				if (((previousValue != value) 
							|| (this._course_tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course_tbl.Entity = null;
						previousValue.enrollment_tbls.Remove(this);
					}
					this._course_tbl.Entity = value;
					if ((value != null))
					{
						value.enrollment_tbls.Add(this);
						this._course_id = value.course_id;
					}
					else
					{
						this._course_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("course_tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stud_account_enrollment_tbl", Storage="_stud_account", ThisKey="stud_id", OtherKey="stud_id", IsForeignKey=true)]
		public stud_account stud_account
		{
			get
			{
				return this._stud_account.Entity;
			}
			set
			{
				stud_account previousValue = this._stud_account.Entity;
				if (((previousValue != value) 
							|| (this._stud_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._stud_account.Entity = null;
						previousValue.enrollment_tbls.Remove(this);
					}
					this._stud_account.Entity = value;
					if ((value != null))
					{
						value.enrollment_tbls.Add(this);
						this._stud_id = value.stud_id;
					}
					else
					{
						this._stud_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("stud_account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ins_tbl")]
	public partial class ins_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ins_id;
		
		private string _ins_fname;
		
		private string _ins_lname;
		
		private System.Nullable<int> _subject_id;
		
		private EntityRef<subject_tbl> _subject_tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onins_idChanging(int value);
    partial void Onins_idChanged();
    partial void Onins_fnameChanging(string value);
    partial void Onins_fnameChanged();
    partial void Onins_lnameChanging(string value);
    partial void Onins_lnameChanged();
    partial void Onsubject_idChanging(System.Nullable<int> value);
    partial void Onsubject_idChanged();
    #endregion
		
		public ins_tbl()
		{
			this._subject_tbl = default(EntityRef<subject_tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ins_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ins_id
		{
			get
			{
				return this._ins_id;
			}
			set
			{
				if ((this._ins_id != value))
				{
					this.Onins_idChanging(value);
					this.SendPropertyChanging();
					this._ins_id = value;
					this.SendPropertyChanged("ins_id");
					this.Onins_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ins_fname", DbType="VarChar(50)")]
		public string ins_fname
		{
			get
			{
				return this._ins_fname;
			}
			set
			{
				if ((this._ins_fname != value))
				{
					this.Onins_fnameChanging(value);
					this.SendPropertyChanging();
					this._ins_fname = value;
					this.SendPropertyChanged("ins_fname");
					this.Onins_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ins_lname", DbType="VarChar(50)")]
		public string ins_lname
		{
			get
			{
				return this._ins_lname;
			}
			set
			{
				if ((this._ins_lname != value))
				{
					this.Onins_lnameChanging(value);
					this.SendPropertyChanging();
					this._ins_lname = value;
					this.SendPropertyChanged("ins_lname");
					this.Onins_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_id", DbType="Int")]
		public System.Nullable<int> subject_id
		{
			get
			{
				return this._subject_id;
			}
			set
			{
				if ((this._subject_id != value))
				{
					if (this._subject_tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsubject_idChanging(value);
					this.SendPropertyChanging();
					this._subject_id = value;
					this.SendPropertyChanged("subject_id");
					this.Onsubject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="subject_tbl_ins_tbl", Storage="_subject_tbl", ThisKey="subject_id", OtherKey="subject_id", IsForeignKey=true)]
		public subject_tbl subject_tbl
		{
			get
			{
				return this._subject_tbl.Entity;
			}
			set
			{
				subject_tbl previousValue = this._subject_tbl.Entity;
				if (((previousValue != value) 
							|| (this._subject_tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._subject_tbl.Entity = null;
						previousValue.ins_tbls.Remove(this);
					}
					this._subject_tbl.Entity = value;
					if ((value != null))
					{
						value.ins_tbls.Add(this);
						this._subject_id = value.subject_id;
					}
					else
					{
						this._subject_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("subject_tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subject_tbl")]
	public partial class subject_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _subject_id;
		
		private string _subject_code;
		
		private string _subject_name;
		
		private System.Nullable<int> _subject_unit;
		
		private System.Nullable<int> _course_id;
		
		private System.Nullable<int> _ins_id;
		
		private EntitySet<ins_tbl> _ins_tbls;
		
		private EntityRef<course_tbl> _course_tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsubject_idChanging(int value);
    partial void Onsubject_idChanged();
    partial void Onsubject_codeChanging(string value);
    partial void Onsubject_codeChanged();
    partial void Onsubject_nameChanging(string value);
    partial void Onsubject_nameChanged();
    partial void Onsubject_unitChanging(System.Nullable<int> value);
    partial void Onsubject_unitChanged();
    partial void Oncourse_idChanging(System.Nullable<int> value);
    partial void Oncourse_idChanged();
    partial void Onins_idChanging(System.Nullable<int> value);
    partial void Onins_idChanged();
    #endregion
		
		public subject_tbl()
		{
			this._ins_tbls = new EntitySet<ins_tbl>(new Action<ins_tbl>(this.attach_ins_tbls), new Action<ins_tbl>(this.detach_ins_tbls));
			this._course_tbl = default(EntityRef<course_tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int subject_id
		{
			get
			{
				return this._subject_id;
			}
			set
			{
				if ((this._subject_id != value))
				{
					this.Onsubject_idChanging(value);
					this.SendPropertyChanging();
					this._subject_id = value;
					this.SendPropertyChanged("subject_id");
					this.Onsubject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_code", DbType="VarChar(10)")]
		public string subject_code
		{
			get
			{
				return this._subject_code;
			}
			set
			{
				if ((this._subject_code != value))
				{
					this.Onsubject_codeChanging(value);
					this.SendPropertyChanging();
					this._subject_code = value;
					this.SendPropertyChanged("subject_code");
					this.Onsubject_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_name", DbType="VarChar(50)")]
		public string subject_name
		{
			get
			{
				return this._subject_name;
			}
			set
			{
				if ((this._subject_name != value))
				{
					this.Onsubject_nameChanging(value);
					this.SendPropertyChanging();
					this._subject_name = value;
					this.SendPropertyChanged("subject_name");
					this.Onsubject_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_unit", DbType="Int")]
		public System.Nullable<int> subject_unit
		{
			get
			{
				return this._subject_unit;
			}
			set
			{
				if ((this._subject_unit != value))
				{
					this.Onsubject_unitChanging(value);
					this.SendPropertyChanging();
					this._subject_unit = value;
					this.SendPropertyChanged("subject_unit");
					this.Onsubject_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="Int")]
		public System.Nullable<int> course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					if (this._course_tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ins_id", DbType="Int")]
		public System.Nullable<int> ins_id
		{
			get
			{
				return this._ins_id;
			}
			set
			{
				if ((this._ins_id != value))
				{
					this.Onins_idChanging(value);
					this.SendPropertyChanging();
					this._ins_id = value;
					this.SendPropertyChanged("ins_id");
					this.Onins_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="subject_tbl_ins_tbl", Storage="_ins_tbls", ThisKey="subject_id", OtherKey="subject_id")]
		public EntitySet<ins_tbl> ins_tbls
		{
			get
			{
				return this._ins_tbls;
			}
			set
			{
				this._ins_tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_tbl_subject_tbl", Storage="_course_tbl", ThisKey="course_id", OtherKey="course_id", IsForeignKey=true)]
		public course_tbl course_tbl
		{
			get
			{
				return this._course_tbl.Entity;
			}
			set
			{
				course_tbl previousValue = this._course_tbl.Entity;
				if (((previousValue != value) 
							|| (this._course_tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course_tbl.Entity = null;
						previousValue.subject_tbls.Remove(this);
					}
					this._course_tbl.Entity = value;
					if ((value != null))
					{
						value.subject_tbls.Add(this);
						this._course_id = value.course_id;
					}
					else
					{
						this._course_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("course_tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ins_tbls(ins_tbl entity)
		{
			this.SendPropertyChanging();
			entity.subject_tbl = this;
		}
		
		private void detach_ins_tbls(ins_tbl entity)
		{
			this.SendPropertyChanging();
			entity.subject_tbl = null;
		}
	}
	
	public partial class check_passwordResult
	{
		
		private string _pass;
		
		public check_passwordResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this._pass = value;
				}
			}
		}
	}
	
	public partial class check_usernameResult
	{
		
		private string _username;
		
		public check_usernameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
	}
	
	public partial class check_studentaccResult
	{
		
		private string _stud_username;
		
		public check_studentaccResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_username", DbType="VarChar(50)")]
		public string stud_username
		{
			get
			{
				return this._stud_username;
			}
			set
			{
				if ((this._stud_username != value))
				{
					this._stud_username = value;
				}
			}
		}
	}
	
	public partial class check_studentpassResult
	{
		
		private string _stud_username;
		
		public check_studentpassResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_username", DbType="VarChar(50)")]
		public string stud_username
		{
			get
			{
				return this._stud_username;
			}
			set
			{
				if ((this._stud_username != value))
				{
					this._stud_username = value;
				}
			}
		}
	}
	
	public partial class get_courseResult
	{
		
		private string _course_name;
		
		public get_courseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this._course_name = value;
				}
			}
		}
	}
	
	public partial class get_infoResult
	{
		
		private string _stud_lname;
		
		private string _stud_fname;
		
		private string _stud_mname;
		
		public get_infoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50)")]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this._stud_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50)")]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this._stud_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_mname", DbType="VarChar(50)")]
		public string stud_mname
		{
			get
			{
				return this._stud_mname;
			}
			set
			{
				if ((this._stud_mname != value))
				{
					this._stud_mname = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
